### ISSUE TITLE
Is this if/else swap or actual if inversion, also any releases/binaries?

### ISSUE THREAD

**Issue by MrSapps** [ecx86/IDA7-HexRays-InvertIf#1]
As per title. I often find myself wanting to invert a condition an if is checking. For instance:

```
if (!a || !b)
{
}
````

I would like to invert to be:

```
if (a && b)
{
}
````

Is that what this plugin does? Also if so would it be possible to compile and upload a release? Having to get the SDK and build etc to test this is quite tedious ;).

**Comment by rcx** [comment]
No, unfortunately it doesn’t support De Morgan’s law. I recommend you to
use HexRaysPyTools which is a python plugin which doesn’t need compilation
and has more features. You can find it on Github :-)

**Comment by MrSapps** [comment]
I've opened a similar issue there too. It appears that plugin does not support it either.
